#spring.application.name=likelion_BE_study
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/likelion_be_study?characterEncoding=UTF-8
    username: root
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: TRUE


logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
        orm:
          jdbc:
            bind: TRACE